
[general]
	rainGrowthSpeed = 3
	useRainGrowthSpeed = true

[individual]
	useIndividualSpeeds = false
	useGeneralSpeedBamboo = true
	bambooCustomSpeed = 10
	useGeneralSpeedCrops = true
	cropsCustomSpeed = 10
	useGeneralSpeedSaplings = true
	saplingCustomSpeed = 10
	useGeneralSpeedSugarCane = true
	sugarCaneCustomSpeed = 10

